### ISSUE TITLE
Revisit workspace tests

### ISSUE THREAD

**Issue by technoweenie** [manifold/tractor#24]
Workspaces boot up automatically now, causing tests to take a long time to run.

    ok  	github.com/manifold/tractor/pkg/agent	26.203s

> The main thing this adds is the subcmd package, which is then used to replace the exec.Cmd code in systray and agent (workspaces). One thing to note is that it changes the state transitions slightly for workspaces. It also starts workspace daemons on start, which also impacts expected states. Tests for Workspace were mostly updated, but I'd say we might want to revisit those tests. Also subcmd needs tests. Perhaps a mock of Subcmd would make the workspace tests cleaner. -- #23

**Comment by progrium** [comment]
sounds like we could use a `subcmd` mock with testify mock? not sure if we need to make an interface for it, but the "architecture" makes it easy to replace any dependency on the struct.
