### ISSUE TITLE
fresh installation woes

### ISSUE THREAD

**Issue by technoweenie** [manifold/tractor#60]
I removed my existing copy and then cloned `github.com/manifold/tractor` to my project directory. Then I ran the following commands:

1. `make setup`, failed on `gyp`. See [attempt-1.txt](https://gist.github.com/technoweenie/6ac14eb84e53de67e31bc05659372f98#file-attempt-1-txt).

```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/rick/p/tractor/studio/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/Cellar/node@10/10.19.0/bin/node" "/Users/rick/p/tractor/studio/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/rick/p/tractor/studio/node_modules/nsfw
```

I do have the xcode cli tools installed.

```sh
$ xcode-select -v
xcode-select version 2373.
```

2. Ran `make qtalk`, then `make setup`. I got some errors like:

```
src/browser/tractor-service.ts:29:23 - error TS2307: Cannot find module 'qmux/dist/browser/qmux.min.js'.

29 import * as qmux from 'qmux/dist/browser/qmux.min.js';
```

So, I ran the following, which succeeded. See [finish-maybe.txt](https://gist.github.com/technoweenie/6ac14eb84e53de67e31bc05659372f98#file-finish-maybe-txt).

```sh
$ yarn link qmux
$ yarn link qrpc
$ make setup
```

3. `make dev` gets this recurring error with some `nsfw` package. See [make-dev.txt](https://gist.github.com/technoweenie/6ac14eb84e53de67e31bc05659372f98#file-make-dev-txt).

Here's what I have installed:

```sh
$ make versions
go version go1.13.6 darwin/amd64
node v10.19.0
git version 2.21.1 (Apple Git-122.3)
yarn 1.22.0
typescript Version 3.7.5
```

I have Python 3.7.6 installed via homebrew, but it's only accessible as `python3`. Running `python` uses 2.7, which I'm guessing is for some legacy mac thing.

**Comment by progrium** [comment]
Alright I think most of this is just related to the first issue which according to many other projects (like https://github.com/schnerd/d3-scale-cluster/issues/7) that have the same dependency and issue, it seems you just have to run `xcode-select --install` again even if it's there. Probably needs to be updated or something, but I think it's more complicated and so yea I think the solution is if you run into that problem with node-gym you reinstall CLI tools.

Now be sure you're working with latest master too!

**Comment by technoweenie** [comment]
Wow, that was an adventure. Thanks for the pointer! Once my laptop passed the [acid test](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#the-acid-test), `make setup` on a fresh tractor clone worked without a hitch.

**Comment by progrium** [comment]
Ooo good find. Haha its such a widespread issue they have a dedicated root level markdown file about it.
