### ISSUE TITLE
studio plugins not loading

### ISSUE THREAD

**Issue by technoweenie** [manifold/tractor#61]
I think they're just not being compiled from typescript to javascript:

```
root ERROR [hosted-plugin: 15432] { Error: Cannot find module '/Users/rick/p/tractor/studio/plugins/tableview/lib/tableview-backend.js'
root ERROR [hosted-plugin: 15432] { Error: Cannot find module '/Users/rick/p/tractor/studio/plugins/moduleview/lib/moduleview-backend.js'
root ERROR [hosted-plugin: 15432] { Error: Cannot find module '/Users/rick/p/tractor/studio/plugins/inspector/lib/inspector-backend.js'
```

**Comment by progrium** [comment]
ah hah!

**Comment by technoweenie** [comment]
Easy fix:

```sh
$ tsc -p studio/plugins/tableview
$ tsc -p studio/plugins/moduleview
$ tsc -p studio/plugins/inspector
```

**Comment by technoweenie** [comment]
Is `make setup` really the best place? The only other spot that compiles them is the watcher loop in the `selfdev` service. So if I happen to edit one of the plugins without starting `tractor-agent --dev`, then it won't be picked up. Am I missing some other step?

Though, since `make dev` runs the `local/bin/tractor-agent`, I suppose it makes sense that you run `make setup` to compile the Go AND Typescript. Is that the intention?

**Comment by technoweenie** [comment]
Fixed by compiling them in the makefile.
