### ISSUE TITLE
force google chrome

### ISSUE THREAD

**Issue by technoweenie** [manifold/tractor#65]
It looks like webviews in theia don't work in firefox, due to an [old bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1433933). Basically, Firefox doesn't treat `*.localhost` domains as secure content. Theia webviews use dynamic localhost names for plugins, leading to this:

<img width="540" alt="Screen Shot 2020-02-20 at 6 02 05 PM" src="https://user-images.githubusercontent.com/21/74994394-40fe4300-540b-11ea-93a4-41400991cd0d.png">

For REASONS, I prefer Firefox. I'd like to force Tractor to use Google Chrome. It's easy!

```diff
diff --git a/pkg/agent/systray/service.go b/pkg/agent/systray/service.go
index 56a41fd..653db16 100644
--- a/pkg/agent/systray/service.go
+++ b/pkg/agent/systray/service.go
@@ -113,7 +113,7 @@ func (s *Service) Serve(ctx context.Context) {
                                }
                                for _, ws := range workspaces {
                                        if ws.Name == msg.Item.Title {
-                                               open.Start("http://localhost:3000/#" + ws.TargetPath)
+                                               open.StartWith("http://localhost:3000/#"+ws.TargetPath, "Google Chrome")
                                        }
                                }
                        default:
```

I'm not sure that's the correct approach though. Is the app name going to be the same on linux and windows? What if people want to run theia in some other browser?

Is there somewhere we can store values in `~/.tractor` for this sort of thing? Something like an an env/yaml/cson file?

**Comment by progrium** [comment]
Yeah, interesting. Good idea but no clue what the consistency is across platforms. We'll probably have to experiment. Yes, we can store config in `~/.tractor` maybe toml?

**Comment by technoweenie** [comment]
I can play around with toml settings in `~/.tractor`. This may open up another can of worms, like passing around some `tractor.Config` struct. Assuming that works favorably, I would want to default to `open.Start()` to rely on the system behavior. I'll see if `github.com/skratchdot/open-golang` will accept a patch where `StartWith()` calls `Start()` if the `appName` arg is empty.

I'll start exploring that. It's a personal race between solving this issue, or going back to Chrome full time 🤣 .

**Comment by technoweenie** [comment]
Easy peasy now:

```sh
$ cat ~/.tractor/config.toml
BrowserPref = "Google Chrome"
```
